version: '3.7'

services:
  client-production:
    container_name: butler-client
    build:
      context: .
      dockerfile: ./app/client/Dockerfile-prod
    ports:
      - 80:80
      - 443:443

  server:
    container_name: butler-server
    build:
      context: .
      dockerfile: ./app/server/Dockerfile
    command: butler
