version: '3.7'

services:
  client-production:
    container_name: butler-client
    image: butlerformeetings/butler-front:latest
    depends_on:
      - server
    ports:
      - 80:80
      - 443:443

  server:
    container_name: butler-server
    image: butlerformeetings/butler-api:latest
    command: butler
