version: '3.7'

services:
  client:
    container_name: butler-client
    build:
      context: .
      dockerfile: ./.docker/development/DOCKERFILE
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '8081:8081'
