version: '3.7'

services:
  client:
    container_name: butler-client
    build:
      context: .
      dockerfile: ./app/client/Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 8081:8081
    expose:
      - 8081

  server:
      container_name: butler-server
      build:
        context: .
        dockerfile: ./app/server/Dockerfile
      volumes:
        - .:/app
      ports:
        - 5000:5000
      expose:
        - 5000

  nginx:
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./app/client/dist:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 80:80
      - 443:443
